### ISSUE TITLE
Should we mark this repo deprecated?

### ISSUE THREAD

**Issue by mattip** [numpy/windows-wheel-builder#6]
It seems we are now building windows wheels via https://github.com/MacPython/numpy-wheels, so should we update the README of this repo to indicate it is not current?

**Comment by matthew-brett** [comment]
Yes, this one can be gutted down to 'nothing to see here' and deprecated.

**Comment by eric-wieser** [comment]
This can be closed now I think, @rgommers

**Comment by rgommers** [comment]
Looks like the `numpy-core` team is missing some permissions on this repo (and perhaps other repos), I'll add those
